"""Modelos de datos - Exporte centralizado"""
from .schemas import (
    LecturaSensor,
    LecturaSensorCreate,
    LecturaSensorHistorial,
    EventoRiego,
    EventoRiegoCreate,
    Configuracion,
    ConfiguracionCreate,
    PronosticoClima,
    RiegoAccion,
    EstadoRiego,
    ControlRiegoManual,
    RespuestaControl,
    ActualizarUmbral,
    ActualizarIntervalo,
    InformacionClima,
    RespuestaExito,
    RespuestaError,
    DashboardActual,
)

__all__ = [
    "LecturaSensor",
    "LecturaSensorCreate",
    "LecturaSensorHistorial",
    "EventoRiego",
    "EventoRiegoCreate",
    "Configuracion",
    "ConfiguracionCreate",
    "PronosticoClima",
    "RiegoAccion",
    "EstadoRiego",
    "ControlRiegoManual",
    "RespuestaControl",
    "ActualizarUmbral",
    "ActualizarIntervalo",
    "InformacionClima",
    "RespuestaExito",
    "RespuestaError",
    "DashboardActual",
]
