BEGIN;

-- 1. Catalogo de ciudades
CREATE TABLE IF NOT EXISTS ciudades (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre varchar(100) NOT NULL UNIQUE,
    codigo_pais varchar(5)
);

-- 2. Dispositivos
CREATE TABLE IF NOT EXISTS dispositivos (
    id varchar(50) PRIMARY KEY,
    nombre varchar(100) NOT NULL,
    ciudad_id integer NOT NULL REFERENCES ciudades(id),
    ubicacion_detallada varchar(200),
    activo boolean NOT NULL DEFAULT true,
    actualizado timestamptz NOT NULL DEFAULT now(),
    creado timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_dispositivos_ciudad_id
    ON dispositivos (ciudad_id);

-- 3. Lecturas
CREATE TABLE IF NOT EXISTS lecturas_sensores (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dispositivo_id varchar(50) NOT NULL REFERENCES dispositivos (id) ON DELETE CASCADE,
    humedad double precision NOT NULL CHECK (humedad BETWEEN 0 AND 100),
    temperatura double precision,
    fecha_lectura timestamptz NOT NULL,
    creado timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_lecturas_sensores_dispositivo_fecha_desc
    ON lecturas_sensores (dispositivo_id, fecha_lectura DESC);

-- 4. Eventos de riego
CREATE TABLE IF NOT EXISTS eventos_riego (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dispositivo_id varchar(50) NOT NULL REFERENCES dispositivos (id) ON DELETE CASCADE,
    accion varchar(10) NOT NULL CHECK (accion IN ('ON', 'OFF')),
    duracion_segundos integer DEFAULT 300 CHECK (duracion_segundos >= 0),
    manual boolean DEFAULT false,
    timestamp timestamptz NOT NULL,
    creado timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_eventos_riego_desc
    ON eventos_riego (dispositivo_id, timestamp DESC);

-- 5. Configuracion
CREATE TABLE IF NOT EXISTS configuracion (
    dispositivo_id varchar(50) PRIMARY KEY REFERENCES dispositivos (id) ON DELETE CASCADE,
    umbral_humedad integer DEFAULT 40 CHECK (umbral_humedad BETWEEN 0 AND 100),
    intervalo_lectura_min integer DEFAULT 5 CHECK (intervalo_lectura_min >= 1),
    lluvia_minima_mm double precision DEFAULT 5.0 CHECK (lluvia_minima_mm >= 0),
    horas_pronostico integer DEFAULT 24 CHECK (horas_pronostico >= 1),
    actualizado timestamptz NOT NULL DEFAULT now(),
    creado timestamptz NOT NULL DEFAULT now()
);

-- 6. Pronostico clima
CREATE TABLE IF NOT EXISTS pronostico_clima (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ciudad_id integer NOT NULL REFERENCES ciudades(id) ON DELETE CASCADE,
    fecha_pronostico timestamptz NOT NULL,
    lluvia_esperada_mm double precision DEFAULT 0.0 CHECK (lluvia_esperada_mm >= 0),
    temperatura_max double precision,
    temperatura_min double precision,
    humedad_relativa integer CHECK (humedad_relativa BETWEEN 0 AND 100),
    descripcion varchar(200),
    actualizado timestamptz NOT NULL DEFAULT now(),
    UNIQUE (ciudad_id, fecha_pronostico)
);

-- 7. Logica auto-update (triggers)
CREATE OR REPLACE FUNCTION fn_actualizar_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    NEW.actualizado = now();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER tr_update_dispositivos
    BEFORE UPDATE ON dispositivos
    FOR EACH ROW EXECUTE FUNCTION fn_actualizar_timestamp();

CREATE TRIGGER tr_update_configuracion
    BEFORE UPDATE ON configuracion
    FOR EACH ROW EXECUTE FUNCTION fn_actualizar_timestamp();

CREATE TRIGGER tr_update_pronostico
    BEFORE UPDATE ON pronostico_clima
    FOR EACH ROW EXECUTE FUNCTION fn_actualizar_timestamp();

COMMIT;
